### ISSUE TITLE
Multi-component files do not scope order correctly

### ISSUE THREAD

**Issue by thibmaek** [hiukky/eslint-plugin-hooks#3]
With the following config:

```json
hooks/sort: ["warn", {
  groups: ["useState", "useNetinfo"]
}]
```

A file given multiple components:

```tsx
const Icon = () => {
  // offending line because in the file this hook is used before useState
  const { internetReachable } = useNetInfo();
  return internetReachable ? <Image /> : <Spinner />;
}

const Container = () => {
  const [loading, setLoading] = useState(true);
  const { internetReachable } = useNetInfo();

  useEffect(() => {
    setLoading(internetReachable);
  }, [internetReachable]);
}
```

Seems the rules are not scoped to the component itself, but rather the whole file.

**Comment by thibmaek** [comment]
An example: 
![image](https://user-images.githubusercontent.com/6213695/117676640-05859b00-b1ae-11eb-98af-ff634e42ce58.png)

**Comment by hiukky** [comment]
Hello @thibmaek! thanks for reporting this! really the validation considers the whole file since I considered only one standard component per file.

I have a little running time at the moment, but I will look at that later this week! thanks!

**Comment by hiukky** [comment]
Hello friends! Sorry for the delay, I'm working on it right now, and in the next few hours I'll be releasing version 0.3.0 with this feature.

**Comment by hiukky** [comment]
Version 0.3.0 was released with new validation support for multiple components per file.

Closing this problem.
